use_default_settings: true

server:
  secret_key: "naow-local-search-change-me"
  bind_address: "127.0.0.1"
  port: 8088
  limiter: false
  image_proxy: false

search:
  safe_search: 0
  formats:
    - html
    - json

outgoing:
  request_timeout: 2.0
